name: Deploy # 部署
 
on: # 触发条件
  push:
    branches:
      - master # 推送到 master 分支 
  release:
    types:
      - published # 推送新版本号
 
  workflow_dispatch: # 手动触发
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout # Checkout 仓库
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Get Date
        run: echo "UPDATE_TIME=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
 
    - name: Setup Node # 安装 Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
 
    - name: Install Hexo # 安装 Hexo
      run: |
        npm install hexo-cli -g
    - name: Cache Modules # 缓存 Node 插件
      uses: actions/cache@v1
      id: cache-modules
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
 
    - name: Install Dependencies # 如果没有缓存或 插件有更新，则安装插件
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: | 
        npm ci
    - name: Deploy # 部署
      id: deploy
      uses: sma11black/hexo-action@v1.0.3
      with:
       deploy_key: ${{ secrets.HEXO_DEPLOY_KEY }}
       user_name: omi_bot
       commit_msg: site update ${{env.UPDATE_TIME}}
    - name: Get output
      run: |
       echo "${{steps.deploy.outputs.notify }}"
